// enhanced main-fixes.js - generated bindings
(function(){
  function qs(s){return document.querySelector(s);} 
  function id(i){return document.getElementById(i);} 
  function safe(fn){ try{ return fn(); }catch(e){ console.warn('safe handler error', e); } }
  function toast(msg){ if(window.showToast) return showToast(msg); try{ console.log(msg); }catch(e){} }

  if(id('actDesc')) id('actDesc').addEventListener('click', function(e){ toast('تم الضغط على actDesc'); });
  if(id('actTitle')) id('actTitle').addEventListener('click', function(e){ toast('تم الضغط على actTitle'); });
  if(id('addRowBtn')) id('addRowBtn').addEventListener('click', function(e){ toast('تم الضغط على addRowBtn'); });
  if(id('alerts')) id('alerts').addEventListener('click', function(e){ toast('تم الضغط على alerts'); });
  if(id('autoCommentary')) id('autoCommentary').addEventListener('click', function(e){ toast('تم الضغط على autoCommentary'); });
  if(id('backHome')) id('backHome').addEventListener('click', function(e){ toast('تم الضغط على backHome'); });
  if(id('balanceChart')) id('balanceChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('balanceSheet')) id('balanceSheet').addEventListener('click', function(e){ toast('تم الضغط على balanceSheet'); });
  if(id('brandDesc')) id('brandDesc').addEventListener('click', function(e){ toast('تم الضغط على brandDesc'); });
  if(id('brandLogo')) id('brandLogo').addEventListener('click', function(e){ toast('تم الضغط على brandLogo'); });
  if(id('brandText')) id('brandText').addEventListener('click', function(e){ toast('تم الضغط على brandText'); });
  if(id('bsAdd')) id('bsAdd').addEventListener('click', function(e){ toast('تم الضغط على bsAdd'); });
  if(id('bsImport')) id('bsImport').addEventListener('click', function(e){ if(typeof parseCSVtoTable==='function'){ var ta=document.querySelector('textarea#csvtext'); if(ta) parseCSVtoTable(ta.value,'#trialBalanceTable'); else toast('لا يوجد نص CSV'); } else toast('دالة التحليل غير متاحة'); });
  if(id('bsTable')) id('bsTable').addEventListener('click', function(e){ toast('تم الضغط على bsTable'); });
  if(id('bsTitle')) id('bsTitle').addEventListener('click', function(e){ toast('تم الضغط على bsTitle'); });
  if(id('btnAddText')) id('btnAddText').addEventListener('click', function(e){ toast('تم الضغط على btnAddText'); });
  if(id('btnClearAll')) id('btnClearAll').addEventListener('click', function(e){ var tb=document.querySelector('#trialBalanceTable tbody'); if(tb){ tb.innerHTML=''; toast('تم المسح'); } else toast('لا يوجد جدول للحذف'); });
  if(id('btnClearText')) id('btnClearText').addEventListener('click', function(e){ var tb=document.querySelector('#trialBalanceTable tbody'); if(tb){ tb.innerHTML=''; toast('تم المسح'); } else toast('لا يوجد جدول للحذف'); });
  if(id('btnDashText')) id('btnDashText').addEventListener('click', function(e){ toast('تم الضغط على btnDashText'); });
  if(id('btnFillManual')) id('btnFillManual').addEventListener('click', function(e){ toast('تم الضغط على btnFillManual'); });
  if(id('btnLoadText')) id('btnLoadText').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('btnReportText')) id('btnReportText').addEventListener('click', function(e){ window.location = 'report.html'; });
  if(id('btnSaveText')) id('btnSaveText').addEventListener('click', function(e){ if(typeof saveSession==='function') saveSession(); else toast('حفظ الجلسة غير متوفر'); });
  if(id('btnToReport')) id('btnToReport').addEventListener('click', function(e){ window.location = 'report.html'; });
  if(id('btnUploadFile')) id('btnUploadFile').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('btnValidateText')) id('btnValidateText').addEventListener('click', function(e){ toast('تم الضغط على btnValidateText'); });
  if(id('cashChart')) id('cashChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('cashFlow')) id('cashFlow').addEventListener('click', function(e){ toast('تم الضغط على cashFlow'); });
  if(id('catTitle')) id('catTitle').addEventListener('click', function(e){ toast('تم الضغط على catTitle'); });
  if(id('categoryChart')) id('categoryChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('cfAdd')) id('cfAdd').addEventListener('click', function(e){ toast('تم الضغط على cfAdd'); });
  if(id('cfTable')) id('cfTable').addEventListener('click', function(e){ toast('تم الضغط على cfTable'); });
  if(id('cfTitle')) id('cfTitle').addEventListener('click', function(e){ toast('تم الضغط على cfTitle'); });
  if(id('chartActivity')) id('chartActivity').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('chartFinance')) id('chartFinance').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('chartForecast')) id('chartForecast').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('chartLiquidity')) id('chartLiquidity').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('chartProfit')) id('chartProfit').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('clearBtn')) id('clearBtn').addEventListener('click', function(e){ var tb=document.querySelector('#trialBalanceTable tbody'); if(tb){ tb.innerHTML=''; toast('تم المسح'); } else toast('لا يوجد جدول للحذف'); });
  if(id('compareArea')) id('compareArea').addEventListener('click', function(e){ toast('تم الضغط على compareArea'); });
  if(id('compareBtn')) id('compareBtn').addEventListener('click', function(e){ toast('تم الضغط على compareBtn'); });
  if(id('compareChart')) id('compareChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('comparisonChart')) id('comparisonChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('comparisonResults')) id('comparisonResults').addEventListener('click', function(e){ toast('تم الضغط على comparisonResults'); });
  if(id('comparisonTables')) id('comparisonTables').addEventListener('click', function(e){ toast('تم الضغط على comparisonTables'); });
  if(id('currency')) id('currency').addEventListener('click', function(e){ toast('تم الضغط على currency'); });
  if(id('currencySelect')) id('currencySelect').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });
  if(id('darkModeToggle')) id('darkModeToggle').addEventListener('click', function(e){ if(typeof toggleDarkMode==='function') toggleDarkMode(); else document.body.classList.toggle('dark'); });
  if(id('darkToggle')) id('darkToggle').addEventListener('click', function(e){ if(typeof toggleDarkMode==='function') toggleDarkMode(); else document.body.classList.toggle('dark'); });
  if(id('doCompare')) id('doCompare').addEventListener('click', function(e){ toast('تم الضغط على doCompare'); });
  if(id('eqAdd')) id('eqAdd').addEventListener('click', function(e){ toast('تم الضغط على eqAdd'); });
  if(id('eqTable')) id('eqTable').addEventListener('click', function(e){ toast('تم الضغط على eqTable'); });
  if(id('eqTitle')) id('eqTitle').addEventListener('click', function(e){ toast('تم الضغط على eqTitle'); });
  if(id('equity')) id('equity').addEventListener('click', function(e){ toast('تم الضغط على equity'); });
  if(id('equityChart')) id('equityChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('exportComparisonExcel')) id('exportComparisonExcel').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportComparisonPdf')) id('exportComparisonPdf').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportDoc')) id('exportDoc').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportDocxBtn')) id('exportDocxBtn').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportExcel')) id('exportExcel').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportExcelBtn')) id('exportExcelBtn').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportPdf')) id('exportPdf').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportPdfBtn')) id('exportPdfBtn').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('exportPdfBtnHeader')) id('exportPdfBtnHeader').addEventListener('click', function(e){ if(typeof exportReportToPdf==='function') exportReportToPdf('report-area','report.pdf'); else if(typeof html2pdf!=='undefined') { try{ html2pdf().from(document.getElementById('report-area')||document.body).save('report.pdf'); }catch(er){toast('فشل التصدير')}} else toast('تصدير PDF غير متاح'); });
  if(id('f1Desc')) id('f1Desc').addEventListener('click', function(e){ toast('تم الضغط على f1Desc'); });
  if(id('f1Title')) id('f1Title').addEventListener('click', function(e){ toast('تم الضغط على f1Title'); });
  if(id('f2Desc')) id('f2Desc').addEventListener('click', function(e){ toast('تم الضغط على f2Desc'); });
  if(id('f2Title')) id('f2Title').addEventListener('click', function(e){ toast('تم الضغط على f2Title'); });
  if(id('f3Desc')) id('f3Desc').addEventListener('click', function(e){ toast('تم الضغط على f3Desc'); });
  if(id('f3Title')) id('f3Title').addEventListener('click', function(e){ toast('تم الضغط على f3Title'); });
  if(id('fileInput')) id('fileInput').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });
  if(id('fileInput1')) id('fileInput1').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });
  if(id('fileInput2')) id('fileInput2').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });
  if(id('finDesc')) id('finDesc').addEventListener('click', function(e){ toast('تم الضغط على finDesc'); });
  if(id('finTitle')) id('finTitle').addEventListener('click', function(e){ toast('تم الضغط على finTitle'); });
  if(id('financialTables')) id('financialTables').addEventListener('click', function(e){ toast('تم الضغط على financialTables'); });
  if(id('foreDesc')) id('foreDesc').addEventListener('click', function(e){ toast('تم الضغط على foreDesc'); });
  if(id('foreTitle')) id('foreTitle').addEventListener('click', function(e){ toast('تم الضغط على foreTitle'); });
  if(id('forecastChart')) id('forecastChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('forecastMethod')) id('forecastMethod').addEventListener('click', function(e){ toast('تم الضغط على forecastMethod'); });
  if(id('fxInput')) id('fxInput').addEventListener('click', function(e){ toast('تم الضغط على fxInput'); });
  if(id('fxLabel')) id('fxLabel').addEventListener('click', function(e){ toast('تم الضغط على fxLabel'); });
  if(id('fxRateInput')) id('fxRateInput').addEventListener('click', function(e){ toast('تم الضغط على fxRateInput'); });
  if(id('fxWrap')) id('fxWrap').addEventListener('click', function(e){ toast('تم الضغط على fxWrap'); });
  if(id('goDashboardBtn')) id('goDashboardBtn').addEventListener('click', function(e){ toast('تم الضغط على goDashboardBtn'); });
  if(id('goReportBtn')) id('goReportBtn').addEventListener('click', function(e){ window.location = 'report.html'; });
  if(id('hero-text')) id('hero-text').addEventListener('click', function(e){ toast('تم الضغط على hero-text'); });
  if(id('hero-title')) id('hero-title').addEventListener('click', function(e){ toast('تم الضغط على hero-title'); });
  if(id('heroTitle')) id('heroTitle').addEventListener('click', function(e){ toast('تم الضغط على heroTitle'); });
  if(id('horizonInput')) id('horizonInput').addEventListener('click', function(e){ toast('تم الضغط على horizonInput'); });
  if(id('incomeChart')) id('incomeChart').addEventListener('click', function(e){ if(typeof exportChartAsPNG==='function') exportChartAsPNG('#chartMain','chart.png'); else toast('تصدير الرسم غير متاح'); });
  if(id('incomeStatement')) id('incomeStatement').addEventListener('click', function(e){ toast('تم الضغط على incomeStatement'); });
  if(id('isAdd')) id('isAdd').addEventListener('click', function(e){ toast('تم الضغط على isAdd'); });
  if(id('isTable')) id('isTable').addEventListener('click', function(e){ toast('تم الضغط على isTable'); });
  if(id('isTitle')) id('isTitle').addEventListener('click', function(e){ toast('تم الضغط على isTitle'); });
  if(id('kpiRow')) id('kpiRow').addEventListener('click', function(e){ toast('تم الضغط على kpiRow'); });
  if(id('kpiSection')) id('kpiSection').addEventListener('click', function(e){ toast('تم الضغط على kpiSection'); });
  if(id('kpiTitle')) id('kpiTitle').addEventListener('click', function(e){ toast('تم الضغط على kpiTitle'); });
  if(id('lang')) id('lang').addEventListener('click', function(e){ toast('تم الضغط على lang'); });
  if(id('langSelect')) id('langSelect').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });
  if(id('langToggle')) id('langToggle').addEventListener('click', function(e){ toast('تم الضغط على langToggle'); });
  if(id('languageSelect')) id('languageSelect').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });
  if(id('liqDesc')) id('liqDesc').addEventListener('click', function(e){ toast('تم الضغط على liqDesc'); });
  if(id('liqTitle')) id('liqTitle').addEventListener('click', function(e){ toast('تم الضغط على liqTitle'); });
  if(id('loadA')) id('loadA').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('loadB')) id('loadB').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('loadBtn')) id('loadBtn').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('loadLocalBtn')) id('loadLocalBtn').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('mainArea')) id('mainArea').addEventListener('click', function(e){ toast('تم الضغط على mainArea'); });
  if(id('mappingFile')) id('mappingFile').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });
  if(id('out')) id('out').addEventListener('click', function(e){ toast('تم الضغط على out'); });
  if(id('pageTitle')) id('pageTitle').addEventListener('click', function(e){ toast('تم الضغط على pageTitle'); });
  if(id('paneBS')) id('paneBS').addEventListener('click', function(e){ toast('تم الضغط على paneBS'); });
  if(id('paneCF')) id('paneCF').addEventListener('click', function(e){ toast('تم الضغط على paneCF'); });
  if(id('paneEQ')) id('paneEQ').addEventListener('click', function(e){ toast('تم الضغط على paneEQ'); });
  if(id('paneIS')) id('paneIS').addEventListener('click', function(e){ toast('تم الضغط على paneIS'); });
  if(id('particleCanvas')) id('particleCanvas').addEventListener('click', function(e){ toast('تم الضغط على particleCanvas'); });
  if(id('particles')) id('particles').addEventListener('click', function(e){ toast('تم الضغط على particles'); });
  if(id('previewTitle')) id('previewTitle').addEventListener('click', function(e){ toast('تم الضغط على previewTitle'); });
  if(id('profDesc')) id('profDesc').addEventListener('click', function(e){ toast('تم الضغط على profDesc'); });
  if(id('profTitle')) id('profTitle').addEventListener('click', function(e){ toast('تم الضغط على profTitle'); });
  if(id('ratiosArea')) id('ratiosArea').addEventListener('click', function(e){ toast('تم الضغط على ratiosArea'); });
  if(id('refreshBtn')) id('refreshBtn').addEventListener('click', function(e){ toast('تم الضغط على refreshBtn'); });
  if(id('ribbonDesc')) id('ribbonDesc').addEventListener('click', function(e){ toast('تم الضغط على ribbonDesc'); });
  if(id('ribbonTitle')) id('ribbonTitle').addEventListener('click', function(e){ toast('تم الضغط على ribbonTitle'); });
  if(id('runForecast')) id('runForecast').addEventListener('click', function(e){ toast('تم الضغط على runForecast'); });
  if(id('saveBtn')) id('saveBtn').addEventListener('click', function(e){ if(typeof saveSession==='function') saveSession(); else toast('حفظ الجلسة غير متوفر'); });
  if(id('saveLocalBtn')) id('saveLocalBtn').addEventListener('click', function(e){ if(typeof saveSession==='function') saveSession(); else toast('حفظ الجلسة غير متوفر'); });
  if(id('saveSettings')) id('saveSettings').addEventListener('click', function(e){ if(typeof saveSession==='function') saveSession(); else toast('حفظ الجلسة غير متوفر'); });
  if(id('saveSnap')) id('saveSnap').addEventListener('click', function(e){ if(typeof saveSession==='function') saveSession(); else toast('حفظ الجلسة غير متوفر'); });
  if(id('snapA')) id('snapA').addEventListener('click', function(e){ toast('تم الضغط على snapA'); });
  if(id('snapB')) id('snapB').addEventListener('click', function(e){ toast('تم الضغط على snapB'); });
  if(id('startBtn')) id('startBtn').addEventListener('click', function(e){ toast('تم الضغط على startBtn'); });
  if(id('startTourBtn')) id('startTourBtn').addEventListener('click', function(e){ toast('تم الضغط على startTourBtn'); });
  if(id('statTabs')) id('statTabs').addEventListener('click', function(e){ toast('تم الضغط على statTabs'); });
  if(id('tabBS')) id('tabBS').addEventListener('click', function(e){ toast('تم الضغط على tabBS'); });
  if(id('tabCF')) id('tabCF').addEventListener('click', function(e){ toast('تم الضغط على tabCF'); });
  if(id('tabEQ')) id('tabEQ').addEventListener('click', function(e){ toast('تم الضغط على tabEQ'); });
  if(id('tabIS')) id('tabIS').addEventListener('click', function(e){ toast('تم الضغط على tabIS'); });
  if(id('tablePreview')) id('tablePreview').addEventListener('click', function(e){ toast('تم الضغط على tablePreview'); });
  if(id('tablesTitle')) id('tablesTitle').addEventListener('click', function(e){ toast('تم الضغط على tablesTitle'); });
  if(id('taxInput')) id('taxInput').addEventListener('click', function(e){ toast('تم الضغط على taxInput'); });
  if(id('tbBody')) id('tbBody').addEventListener('click', function(e){ toast('تم الضغط على tbBody'); });
  if(id('title')) id('title').addEventListener('click', function(e){ toast('تم الضغط على title'); });
  if(id('toastArea')) id('toastArea').addEventListener('click', function(e){ toast('تم الضغط على toastArea'); });
  if(id('tourBubble')) id('tourBubble').addEventListener('click', function(e){ toast('تم الضغط على tourBubble'); });
  if(id('tourClose')) id('tourClose').addEventListener('click', function(e){ toast('تم الضغط على tourClose'); });
  if(id('tourNext')) id('tourNext').addEventListener('click', function(e){ toast('تم الضغط على tourNext'); });
  if(id('tourPrev')) id('tourPrev').addEventListener('click', function(e){ toast('تم الضغط على tourPrev'); });
  if(id('tourText')) id('tourText').addEventListener('click', function(e){ toast('تم الضغط على tourText'); });
  if(id('trial-table-title')) id('trial-table-title').addEventListener('click', function(e){ toast('تم الضغط على trial-table-title'); });
  if(id('trialTable')) id('trialTable').addEventListener('click', function(e){ toast('تم الضغط على trialTable'); });
  if(id('uploadHint')) id('uploadHint').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('uploadLabel')) id('uploadLabel').addEventListener('click', function(e){ if(typeof loadSession==='function') loadSession(); else toast('تحميل الجلسة غير متوفر'); });
  if(id('validateAllBtn')) id('validateAllBtn').addEventListener('click', function(e){ toast('تم الضغط على validateAllBtn'); });
  if(id('validateBtn')) id('validateBtn').addEventListener('click', function(e){ toast('تم الضغط على validateBtn'); });
  if(id('validationResult')) id('validationResult').addEventListener('click', function(e){ toast('تم الضغط على validationResult'); });
  if(id('waccInput')) id('waccInput').addEventListener('click', function(e){ toast('تم الضغط على waccInput'); });
  if(id('warningNote')) id('warningNote').addEventListener('click', function(e){ toast('تم الضغط على warningNote'); });
  if(id('wmLogo')) id('wmLogo').addEventListener('click', function(e){ toast('تم الضغط على wmLogo'); });
  if(id('yearSelect')) id('yearSelect').addEventListener('click', function(e){ var fi = document.querySelector('input[type=file]'); if(fi && fi.files && fi.files[0]){ var f = fi.files[0]; if(typeof parseXLSX === 'function' && f.name.toLowerCase().endsWith('.xlsx')){ parseXLSX(f, function(rows){ if(typeof buildTableFromRows==='function') buildTableFromRows(rows); }); return; } var reader=new FileReader(); reader.onload=function(ev){ if(typeof parseCSVtoTable==='function') parseCSVtoTable(ev.target.result, '#trialBalanceTable'); else if(typeof buildTableFromCSV==='function') buildTableFromCSV(ev.target.result); else toast('وحدة التحليل غير متاحة'); }; reader.readAsText(f,'utf-8'); } else toast('اختر ملفاً أولاً'); });

})();
